import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from './components/Footer';
import Script from "next/script";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import 'react-toastify/dist/ReactToastify.css';
import { ThemeProvider } from "@mui/material/styles";
import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased tw-bg-[url('../public/oc-gonzalez-A-11N8ItHZo-unsplash.jpg')] tw-bg-cover tw-bg-no-repeat tw-bg-center`}>
       {/* This loads the reCAPTCHA script once the page is interactive. The src="https://www.google.com/recaptcha/api.js" loads the reCAPTCHA script and this ensures the reCAPTCHA API is loaded on your pages, and then the <div className="g-recaptcha" ...> in the FindMe component will work correctly.. The strategy="afterInteractive" ensures the script is fetched and executed after the page is interactive (which is typically what you want for non-critical scripts). */}
        <Script src="https://www.google.com/recaptcha/api.js"
          strategy="afterInteractive"/>
          <Providers>
            {children}
          </Providers>
          <Footer />
      </body>
    </html>
  );
}
